### ISSUE TITLE
sift 描述子实现问题

### ISSUE THREAD

**Issue by dongzhixihe** [SmallMunich/HessianAffineMatch_VisualStudio2015#1]
看了你的源代码，有些问题。兴趣点的检测结果记录是用的自定义的Keypoint类，为什么不用opencv自带的KeyPoint类呢？而在draw_kpts_ellipse（）函数中的兴趣的却是Opencv自带的KeyPoint类，这样不兼容啊

**Comment by SmallMunich** [comment]
你好，我的实现是基于opencv的Keypoint类，只是仿射参数估计在keypoint类里面没有变量表示，所以我在其对应的头文件添加了相关的仿射变量系数。想要兼容的话，只需要在opencv的keypoint类里面添加我代码里面的变量即可。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: dongzhixihe <notifications@github.com>
发送时间: Monday, May 13, 2019 11:06:42 PM
收件人: SmallMunich/HessianAffineMatch_VisualStudio2015
抄送: Subscribed
主题: [SmallMunich/HessianAffineMatch_VisualStudio2015] sift 描述子实现问题 (#1)


看了你的源代码，有些问题。兴趣点的检测结果记录是用的自定义的Keypoint类，为什么不用opencv自带的KeyPoint类呢？而在draw_kpts_ellipse（）函数中的兴趣的却是Opencv自带的KeyPoint类，这样不兼容啊

―
